"""initial migration

Revision ID: dce620b9f0a4
Revises: 
Create Date: 2020-10-23 09:50:04.427684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce620b9f0a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sorting_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_winner', sa.Boolean(), nullable=False),
    sa.Column('intel', sa.Boolean(), nullable=False),
    sa.Column('lowest_split', sa.Boolean(), nullable=False),
    sa.Column('post_pick_position', sa.Integer(), nullable=False),
    sa.Column('trap', sa.Integer(), nullable=False),
    sa.Column('sp_forecast', sa.String(length=100), nullable=False),
    sa.Column('badges', sa.String(length=50), nullable=False),
    sa.Column('neighbours', sa.Text(length=256), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sorting_query')
    # ### end Alembic commands ###
